### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by ppavlidis**
for the next major release

### CODE REVIEW

**Comment by arteymix** [comment]
Do you want this in the 1.31?

**Comment by ppavlidis** [comment]
> Do you want this in the 1.31?
> 
> It will have to be rebased on the 1.31 branch. You can change the target branch in the PR.

Ideally yes to get things all synched up

**Comment by arteymix** [comment]
Ok, I've just rebased your branch. If you want to do any more work, you will have to reset your local branch.

**Review by arteymix — APPROVED** [review]

**Comment by arteymix** [comment]
I'll wait for the CI to pass and then merge this.

**Pull request merged**
